spring:
 cloud:
   gateway:
     routes:
       - id: employee-app
         uri: lb://EMPLOYEE
         predicates:
           - Path=/employee/**,/auth/**
#        filters:
#           - AuthenticationFilter
              

#       - id: restaurant-service
#         uri: lb://EMPLOYEE
#         predicates:
#           - Path=/auth/**
#         filters:
#           - AuthenticationFilter
#         use when want to apply different filters for same microservice different controller

       - id: order-app
         uri: lb://ORDERSERVICE
         predicates:
           - Path=/order/**
         filters:
           - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
